#!/usr/bin/env python3
"""Generate AI analyses for all 160 SNS광고마케터 1급 exam questions."""

import anthropic
import json
import time
import os
import sys

OUTPUT_FILE = "/Users/julienparkxicloud.com/sesac_qbank_project/questions_with_analysis.json"
PROGRESS_FILE = "/Users/julienparkxicloud.com/sesac_qbank_project/progress.json"

# All 160 questions: A형 (1-80) + B형 (81-160)
QUESTIONS = [
    # === A형 (1-80) ===
    {"id": "A001", "num": 1, "type": "A",
     "question": "다음 중 소셜 미디어 마케팅의 특징으로 가장 적절하지 않은 것은?",
     "options": ["①양방향 소통이 가능하다", "②바이럴 효과를 기대할 수 있다", "③타겟팅이 불가능하다", "④실시간 피드백이 가능하다"],
     "answer": 3},
    {"id": "A002", "num": 2, "type": "A",
     "question": "인스타그램 광고에서 '도달' 목표를 설정할 때 최적화되는 것은?",
     "options": ["①클릭수", "②노출수", "③전환수", "④앱 설치수"],
     "answer": 2},
    {"id": "A003", "num": 3, "type": "A",
     "question": "페이스북 픽셀(Facebook Pixel)의 주요 기능으로 적절하지 않은 것은?",
     "options": ["①웹사이트 방문자 추적", "②전환 추적", "③리타겟팅 광고 집행", "④유기적 게시물 도달 증가"],
     "answer": 4},
    {"id": "A004", "num": 4, "type": "A",
     "question": "CPM(Cost Per Mille)의 의미로 올바른 것은?",
     "options": ["①클릭당 비용", "②1,000회 노출당 비용", "③전환당 비용", "④구매당 비용"],
     "answer": 2},
    {"id": "A005", "num": 5, "type": "A",
     "question": "카카오 비즈니스 광고 상품 중 카카오톡 채널을 활용한 광고 형태는?",
     "options": ["①카카오 디스플레이 광고", "②카카오 검색 광고", "③카카오 채널 메시지", "④카카오 동영상 광고"],
     "answer": 3},
    {"id": "A006", "num": 6, "type": "A",
     "question": "SNS 콘텐츠 마케팅에서 '에버그린 콘텐츠(Evergreen Content)'의 특징은?",
     "options": ["①최신 트렌드를 반영한다", "②시간이 지나도 유용성이 유지된다", "③짧은 수명주기를 가진다", "④특정 계절에만 효과적이다"],
     "answer": 2},
    {"id": "A007", "num": 7, "type": "A",
     "question": "인플루언서 마케팅에서 '마이크로 인플루언서'의 팔로워 수 범위로 가장 적절한 것은?",
     "options": ["①100명 미만", "②1,000~10만 명", "③10만~100만 명", "④100만 명 이상"],
     "answer": 2},
    {"id": "A008", "num": 8, "type": "A",
     "question": "유튜브 광고 형식 중 '건너뛸 수 없는 인스트림 광고'의 최대 길이는?",
     "options": ["①6초", "②15초", "③30초", "④60초"],
     "answer": 2},
    {"id": "A009", "num": 9, "type": "A",
     "question": "SNS 광고의 A/B 테스트에서 변수를 테스트할 때 올바른 방법은?",
     "options": ["①여러 변수를 동시에 변경한다", "②하나의 변수만 변경한다", "③대상 고객을 자주 변경한다", "④예산을 매일 조정한다"],
     "answer": 2},
    {"id": "A010", "num": 10, "type": "A",
     "question": "페이스북 광고 매니저에서 캠페인 구조의 올바른 순서는?",
     "options": ["①캠페인→광고→광고 세트", "②광고 세트→캠페인→광고", "③캠페인→광고 세트→광고", "④광고→광고 세트→캠페인"],
     "answer": 3},
    {"id": "A011", "num": 11, "type": "A",
     "question": "인스타그램에서 쇼핑 태그를 활용하여 제품을 직접 판매할 수 있는 기능은?",
     "options": ["①인스타그램 스토리", "②인스타그램 쇼핑", "③인스타그램 릴스", "④인스타그램 IGTV"],
     "answer": 2},
    {"id": "A012", "num": 12, "type": "A",
     "question": "ROI(Return on Investment) 계산 공식으로 올바른 것은?",
     "options": ["①(수익-비용)/비용×100", "②비용/수익×100", "③수익/비용", "④(비용-수익)/수익×100"],
     "answer": 1},
    {"id": "A013", "num": 13, "type": "A",
     "question": "네이버 밴드 광고의 특징으로 가장 적절한 것은?",
     "options": ["①젊은 층 위주의 사용자", "②그룹 중심의 커뮤니티 광고", "③동영상 전문 플랫폼", "④글로벌 광고 집행"],
     "answer": 2},
    {"id": "A014", "num": 14, "type": "A",
     "question": "소셜 미디어 광고에서 '룩어라이크 타겟팅(Lookalike Targeting)'이란?",
     "options": ["①기존 고객과 유사한 특성의 잠재 고객 타겟팅", "②지역 기반 타겟팅", "③관심사 기반 타겟팅", "④연령 기반 타겟팅"],
     "answer": 1},
    {"id": "A015", "num": 15, "type": "A",
     "question": "콘텐츠 마케팅 깔때기(Content Marketing Funnel)에서 인지(Awareness) 단계에 적합한 콘텐츠는?",
     "options": ["①제품 비교표", "②브랜드 스토리 블로그", "③할인 쿠폰", "④제품 사용 설명서"],
     "answer": 2},
    {"id": "A016", "num": 16, "type": "A",
     "question": "트위터(X) 광고에서 '프로모티드 트윗'의 특징으로 옳은 것은?",
     "options": ["①팔로워에게만 노출된다", "②일반 트윗처럼 보이지만 광고 표시가 된다", "③동영상만 사용 가능하다", "④링크를 포함할 수 없다"],
     "answer": 2},
    {"id": "A017", "num": 17, "type": "A",
     "question": "CTA(Call to Action)의 의미로 올바른 것은?",
     "options": ["①클릭 추적 분석", "②행동 유도 문구", "③고객 타겟 분석", "④전환율 최적화"],
     "answer": 2},
    {"id": "A018", "num": 18, "type": "A",
     "question": "인스타그램 스토리 광고의 특징으로 적절하지 않은 것은?",
     "options": ["①세로형 전체 화면 형식", "②24시간 후 자동 삭제", "③스와이프 업 링크 기능", "④최대 60분 영상 게재 가능"],
     "answer": 4},
    {"id": "A019", "num": 19, "type": "A",
     "question": "소셜 미디어 마케팅에서 KPI(Key Performance Indicator)에 해당하지 않는 것은?",
     "options": ["①참여율", "②도달수", "③경쟁사 매출", "④전환율"],
     "answer": 3},
    {"id": "A020", "num": 20, "type": "A",
     "question": "유튜브 채널 운영 시 '커뮤니티 가이드라인 위반'에 해당하는 것은?",
     "options": ["①저작권 있는 음악 사용", "②스폰서 콘텐츠 표시", "③댓글 관리", "④멤버십 운영"],
     "answer": 1},
    {"id": "A021", "num": 21, "type": "A",
     "question": "페이스북 광고에서 '전환 최적화'를 사용하기 위해 반드시 필요한 것은?",
     "options": ["①페이지 좋아요", "②픽셀 설치", "③동영상 콘텐츠", "④인플루언서 협업"],
     "answer": 2},
    {"id": "A022", "num": 22, "type": "A",
     "question": "소셜 미디어에서 해시태그(#)의 주요 기능으로 적절하지 않은 것은?",
     "options": ["①콘텐츠 분류", "②검색 최적화", "③트렌드 참여", "④계정 팔로우"],
     "answer": 4},
    {"id": "A023", "num": 23, "type": "A",
     "question": "네이버 스마트플레이스 광고의 주요 목적으로 가장 적합한 것은?",
     "options": ["①글로벌 브랜드 인지도 향상", "②지역 기반 오프라인 매장 방문 유도", "③앱 다운로드 증가", "④이커머스 전환 최적화"],
     "answer": 2},
    {"id": "A024", "num": 24, "type": "A",
     "question": "SNS 광고 소재(Creative) 제작 시 이미지 광고의 텍스트 비율 권장 기준(페이스북 기준)은?",
     "options": ["①텍스트 없음", "②20% 이하", "③50% 이하", "④제한 없음"],
     "answer": 2},
    {"id": "A025", "num": 25, "type": "A",
     "question": "브랜디드 콘텐츠(Branded Content) 마케팅의 특징으로 가장 적절한 것은?",
     "options": ["①직접적인 제품 홍보를 전면에 내세운다", "②스토리텔링을 통해 브랜드 가치를 전달한다", "③가격 할인 정보를 주로 제공한다", "④경쟁사와의 비교를 강조한다"],
     "answer": 2},
    {"id": "A026", "num": 26, "type": "A",
     "question": "인스타그램 알고리즘에서 콘텐츠 노출에 영향을 미치는 주요 요소가 아닌 것은?",
     "options": ["①관계성(Relationship)", "②관심도(Interest)", "③시의성(Timeliness)", "④게시 시간대(Posting Time)"],
     "answer": 4},
    {"id": "A027", "num": 27, "type": "A",
     "question": "소셜 미디어 광고에서 '빈도(Frequency)'가 너무 높을 때 발생하는 문제는?",
     "options": ["①도달수 감소", "②광고 피로도 증가", "③클릭률 상승", "④예산 절감"],
     "answer": 2},
    {"id": "A028", "num": 28, "type": "A",
     "question": "카카오 모먼트 광고 상품 중 카카오스토리에 게재되는 광고 형태는?",
     "options": ["①카카오톡 비즈보드", "②카카오 배너 광고", "③카카오스토리 광고", "④카카오 동영상 광고"],
     "answer": 3},
    {"id": "A029", "num": 29, "type": "A",
     "question": "소셜 미디어 마케팅에서 '소셜 리스닝(Social Listening)'의 목적으로 가장 적절한 것은?",
     "options": ["①광고 집행 자동화", "②온라인 대화 모니터링 및 인사이트 수집", "③팔로워 수 증가", "④콘텐츠 자동 생성"],
     "answer": 2},
    {"id": "A030", "num": 30, "type": "A",
     "question": "유튜브 광고에서 '트루뷰 인스트림(TrueView InStream)' 광고의 특징은?",
     "options": ["①항상 건너뛸 수 없다", "②5초 후 건너뛸 수 있다", "③검색 결과에 표시된다", "④배너 형태로 표시된다"],
     "answer": 2},
    {"id": "A031", "num": 31, "type": "A",
     "question": "퍼포먼스 마케팅에서 '어트리뷰션(Attribution)'의 의미는?",
     "options": ["①광고 예산 배분", "②전환에 기여한 채널/접점 분석", "③콘텐츠 제작 방식", "④인플루언서 선별 기준"],
     "answer": 2},
    {"id": "A032", "num": 32, "type": "A",
     "question": "인스타그램 릴스(Reels)의 최대 길이는?",
     "options": ["①15초", "②30초", "③60초", "④90초"],
     "answer": 4},
    {"id": "A033", "num": 33, "type": "A",
     "question": "소셜 미디어 광고의 '게재 최적화(Delivery Optimization)'에서 '링크 클릭' 최적화는 무엇을 극대화하는가?",
     "options": ["①광고 노출 횟수", "②광고를 클릭하는 사람 수", "③페이지 좋아요", "④동영상 조회 수"],
     "answer": 2},
    {"id": "A034", "num": 34, "type": "A",
     "question": "네이버 블로그 마케팅에서 'C-Rank' 알고리즘이 반영하는 주요 요소는?",
     "options": ["①팔로워 수", "②블로그 활동성과 콘텐츠 품질", "③광고 집행 금액", "④외부 링크 수"],
     "answer": 2},
    {"id": "A035", "num": 35, "type": "A",
     "question": "소셜 미디어 마케팅에서 '사용자 생성 콘텐츠(UGC: User Generated Content)'의 장점으로 적절하지 않은 것은?",
     "options": ["①신뢰도 향상", "②비용 절감", "③완벽한 품질 보장", "④커뮤니티 형성"],
     "answer": 3},
    {"id": "A036", "num": 36, "type": "A",
     "question": "페이스북 비즈니스 관리자(Business Manager)의 주요 기능으로 적절하지 않은 것은?",
     "options": ["①여러 광고 계정 관리", "②팀원 권한 설정", "③결제 수단 관리", "④유기적 게시물 작성 전용"],
     "answer": 4},
    {"id": "A037", "num": 37, "type": "A",
     "question": "소셜 미디어 광고에서 '다이나믹 광고(Dynamic Ads)'의 특징은?",
     "options": ["①모든 사용자에게 동일한 광고를 보여준다", "②사용자의 행동에 따라 자동으로 개인화된 광고를 표시한다", "③오직 동영상 형태로만 운영된다", "④수동으로 개별 광고를 생성해야 한다"],
     "answer": 2},
    {"id": "A038", "num": 38, "type": "A",
     "question": "CTR(Click Through Rate) 계산 공식으로 올바른 것은?",
     "options": ["①클릭수/노출수×100", "②노출수/클릭수×100", "③전환수/클릭수×100", "④클릭수/전환수×100"],
     "answer": 1},
    {"id": "A039", "num": 39, "type": "A",
     "question": "인스타그램 비즈니스 계정으로 전환 시 얻을 수 있는 기능으로 적절하지 않은 것은?",
     "options": ["①인사이트(통계) 확인", "②광고 집행", "③쇼핑 기능", "④팔로워 자동 증가"],
     "answer": 4},
    {"id": "A040", "num": 40, "type": "A",
     "question": "소셜 미디어 마케팅 계획 수립 시 SWOT 분석에서 'T(Threat)'에 해당하는 것은?",
     "options": ["①내부 역량", "②시장 기회", "③경쟁사 신제품 출시", "④자사 브랜드 인지도"],
     "answer": 3},
    {"id": "A041", "num": 41, "type": "A",
     "question": "유튜브 채널 최적화를 위한 SEO 요소가 아닌 것은?",
     "options": ["①키워드가 포함된 제목", "②상세한 동영상 설명", "③관련 태그 설정", "④구독자 구매 유도"],
     "answer": 4},
    {"id": "A042", "num": 42, "type": "A",
     "question": "페이스북/인스타그램 광고에서 '맞춤 타겟(Custom Audience)'을 만드는 방법이 아닌 것은?",
     "options": ["①고객 이메일 리스트 업로드", "②웹사이트 방문자(픽셀 기반)", "③앱 활동 기반", "④경쟁사 팔로워 기반"],
     "answer": 4},
    {"id": "A043", "num": 43, "type": "A",
     "question": "SNS 광고에서 '리마케팅(Remarketing)'의 주요 목적은?",
     "options": ["①신규 고객 확보", "②이미 관심을 보인 사용자에게 재노출", "③브랜드 인지도 구축", "④앱 설치 유도"],
     "answer": 2},
    {"id": "A044", "num": 44, "type": "A",
     "question": "네이버 검색 광고에서 '파워링크'의 과금 방식은?",
     "options": ["①CPM", "②CPC", "③CPA", "④CPV"],
     "answer": 2},
    {"id": "A045", "num": 45, "type": "A",
     "question": "소셜 미디어 마케팅에서 '인게이지먼트율(Engagement Rate)' 계산 시 분자에 해당하는 것은?",
     "options": ["①노출수", "②좋아요+댓글+공유 등 반응 합계", "③팔로워 수", "④클릭수"],
     "answer": 2},
    {"id": "A046", "num": 46, "type": "A",
     "question": "틱톡(TikTok) 광고 상품 중 앱 실행 시 전체 화면으로 노출되는 광고 형태는?",
     "options": ["①인피드 광고", "②탑뷰(TopView)", "③브랜드 테이크오버", "④해시태그 챌린지"],
     "answer": 2},
    {"id": "A047", "num": 47, "type": "A",
     "question": "소셜 미디어 콘텐츠 캘린더 작성 시 포함해야 할 요소가 아닌 것은?",
     "options": ["①게시 날짜와 시간", "②콘텐츠 형식", "③경쟁사 비밀 정보", "④게시 채널"],
     "answer": 3},
    {"id": "A048", "num": 48, "type": "A",
     "question": "온라인 광고에서 '뷰어빌리티(Viewability)'란?",
     "options": ["①광고가 실제로 사용자 화면에 보이는 비율", "②광고 클릭률", "③광고 전환율", "④광고 도달 범위"],
     "answer": 1},
    {"id": "A049", "num": 49, "type": "A",
     "question": "페이스북 광고 목표 중 '트래픽' 목표의 주요 최적화 대상은?",
     "options": ["①앱 설치", "②웹사이트 방문", "③동영상 조회", "④도달"],
     "answer": 2},
    {"id": "A050", "num": 50, "type": "A",
     "question": "소셜 미디어 마케팅에서 '고객 여정(Customer Journey)'에서 가장 마지막 단계는?",
     "options": ["①인지(Awareness)", "②고려(Consideration)", "③구매(Purchase)", "④옹호(Advocacy)"],
     "answer": 4},
    {"id": "A051", "num": 51, "type": "A",
     "question": "인스타그램 광고 배치(Placement)에 해당하지 않는 것은?",
     "options": ["①스토리", "②피드", "③탐색 탭", "④메신저 홈"],
     "answer": 4},
    {"id": "A052", "num": 52, "type": "A",
     "question": "소셜 미디어 광고에서 '예산 소진 방식' 중 '일일 예산'의 특징은?",
     "options": ["①캠페인 기간 동안 총 예산을 균등하게 배분한다", "②하루 최대 지출액을 설정한다", "③노출당 비용을 설정한다", "④클릭당 비용을 고정한다"],
     "answer": 2},
    {"id": "A053", "num": 53, "type": "A",
     "question": "유튜브 '범퍼 광고(Bumper Ads)'의 특징으로 올바른 것은?",
     "options": ["①건너뛸 수 있다", "②최대 6초 길이의 건너뛸 수 없는 광고", "③최소 30초이다", "④클릭당 과금된다"],
     "answer": 2},
    {"id": "A054", "num": 54, "type": "A",
     "question": "소셜 미디어 마케팅에서 '소셜 프루프(Social Proof)'의 예로 적절하지 않은 것은?",
     "options": ["①고객 리뷰", "②추천 수", "③브랜드 자체 광고", "④전문가 추천"],
     "answer": 3},
    {"id": "A055", "num": 55, "type": "A",
     "question": "광고 성과 측정에서 ROAS(Return on Ad Spend) 계산 공식은?",
     "options": ["①광고비/매출×100", "②매출/광고비×100", "③(매출-광고비)/광고비", "④광고비/(매출-비용)"],
     "answer": 2},
    {"id": "A056", "num": 56, "type": "A",
     "question": "카카오 광고에서 '카카오톡 비즈보드'의 게재 위치는?",
     "options": ["①카카오스토리 피드", "②카카오톡 채팅 목록 상단", "③카카오맵 검색 결과", "④카카오웹툰 페이지"],
     "answer": 2},
    {"id": "A057", "num": 57, "type": "A",
     "question": "소셜 미디어 마케팅에서 '오가닉(Organic) 도달'이란?",
     "options": ["①광고비를 지불하고 얻은 도달", "②광고비 없이 자연스럽게 달성된 도달", "③인플루언서를 통한 도달", "④이메일 마케팅을 통한 도달"],
     "answer": 2},
    {"id": "A058", "num": 58, "type": "A",
     "question": "페이스북 광고의 '관심사 타겟팅'에서 사용자의 관심사를 파악하는 기준은?",
     "options": ["①광고 클릭 이력", "②좋아요, 팔로우, 앱 사용 등 활동 이력", "③구매 이력", "④위치 정보"],
     "answer": 2},
    {"id": "A059", "num": 59, "type": "A",
     "question": "소셜 미디어 위기 관리(Crisis Management)에서 초기 대응으로 가장 적절한 것은?",
     "options": ["①상황을 무시하고 기다린다", "②신속하게 공식 입장을 발표한다", "③경쟁사를 비난한다", "④모든 SNS 계정을 비공개로 전환한다"],
     "answer": 2},
    {"id": "A060", "num": 60, "type": "A",
     "question": "인스타그램 '협업 게시물(Collab Post)' 기능의 특징은?",
     "options": ["①두 계정이 동일한 게시물을 각자 피드에 공유한다", "②한 계정만 게시물을 소유한다", "③스토리에만 사용 가능하다", "④동영상에만 사용 가능하다"],
     "answer": 1},
    {"id": "A061", "num": 61, "type": "A",
     "question": "소셜 미디어 광고 성과 분석에서 '획득당 비용(CPA: Cost Per Acquisition)'의 의미는?",
     "options": ["①1,000회 노출당 비용", "②클릭 1회당 비용", "③원하는 행동 1건당 비용", "④조회 1회당 비용"],
     "answer": 3},
    {"id": "A062", "num": 62, "type": "A",
     "question": "네이버 밴드에서 '밴드 광고'의 주요 타겟 특성은?",
     "options": ["①10~20대 젊은 층", "②30~50대 중장년층", "③외국인 사용자", "④기업 임원"],
     "answer": 2},
    {"id": "A063", "num": 63, "type": "A",
     "question": "소셜 미디어 마케팅에서 '페이드 미디어(Paid Media)'에 해당하는 것은?",
     "options": ["①자사 블로그", "②자사 SNS 채널", "③SNS 광고", "④고객 리뷰"],
     "answer": 3},
    {"id": "A064", "num": 64, "type": "A",
     "question": "유튜브 '마스트헤드(Masthead)' 광고의 특징은?",
     "options": ["①검색 결과 페이지에 표시된다", "②유튜브 홈피드 최상단에 노출된다", "③동영상 재생 전 표시된다", "④채널 페이지에만 표시된다"],
     "answer": 2},
    {"id": "A065", "num": 65, "type": "A",
     "question": "소셜 미디어 마케팅의 '3E 전략'에 해당하지 않는 것은?",
     "options": ["①교육(Educate)", "②엔터테인(Entertain)", "③참여(Engage)", "④판매(Export)"],
     "answer": 4},
    {"id": "A066", "num": 66, "type": "A",
     "question": "페이스북 광고에서 '도달 및 빈도(Reach and Frequency)' 구매 방식의 특징은?",
     "options": ["①실시간 입찰로 진행된다", "②도달과 빈도를 예측하고 예약하여 구매한다", "③클릭당 과금된다", "④소규모 예산에 적합하다"],
     "answer": 2},
    {"id": "A067", "num": 67, "type": "A",
     "question": "소셜 미디어 광고에서 '광고 피로(Ad Fatigue)'를 방지하는 방법으로 적절하지 않은 것은?",
     "options": ["①소재 교체", "②타겟 확장", "③광고 빈도 증가", "④새로운 형식 시도"],
     "answer": 3},
    {"id": "A068", "num": 68, "type": "A",
     "question": "인플루언서 마케팅 계약 시 반드시 명시해야 할 내용이 아닌 것은?",
     "options": ["①콘텐츠 제작 가이드라인", "②광고 표시 의무", "③인플루언서의 개인 SNS 비밀번호", "④보상 조건"],
     "answer": 3},
    {"id": "A069", "num": 69, "type": "A",
     "question": "소셜 미디어 마케팅에서 '에코 챔버(Echo Chamber)' 현상이란?",
     "options": ["①다양한 의견이 공유되는 현상", "②유사한 견해를 가진 사람들끼리만 소통하는 현상", "③글로벌 트렌드가 확산되는 현상", "④바이럴 콘텐츠가 빠르게 퍼지는 현상"],
     "answer": 2},
    {"id": "A070", "num": 70, "type": "A",
     "question": "카카오 비즈니스에서 '카카오 픽셀 & SDK'의 주요 기능으로 적절하지 않은 것은?",
     "options": ["①광고 성과 측정", "②맞춤 타겟 생성", "③전환 최적화", "④카카오톡 메시지 자동 발송"],
     "answer": 4},
    {"id": "A071", "num": 71, "type": "A",
     "question": "소셜 미디어 광고에서 '인터랙티브 광고(Interactive Ads)'의 특징은?",
     "options": ["①사용자 참여 없이 일방적으로 정보를 전달한다", "②사용자가 광고와 상호작용할 수 있다", "③텍스트만 포함된다", "④TV 광고와 동일한 형식이다"],
     "answer": 2},
    {"id": "A072", "num": 72, "type": "A",
     "question": "유튜브 광고에서 '디스커버리 광고(Discovery Ads)'가 노출되는 위치가 아닌 것은?",
     "options": ["①유튜브 검색 결과", "②관련 동영상 옆", "③유튜브 홈피드", "④동영상 재생 중간"],
     "answer": 4},
    {"id": "A073", "num": 73, "type": "A",
     "question": "소셜 미디어 마케팅에서 '네이티브 광고(Native Advertising)'의 특징은?",
     "options": ["①광고임을 명확히 표시한다", "②플랫폼의 일반 콘텐츠와 유사한 형태를 취한다", "③배너 형태로만 표시된다", "④오직 텍스트만 사용한다"],
     "answer": 2},
    {"id": "A074", "num": 74, "type": "A",
     "question": "페이스북 광고 보고서에서 '노출당 비용(CPM)이 높아졌을 때' 가능한 원인이 아닌 것은?",
     "options": ["①경쟁 심화", "②타겟 고갈", "③광고 관련성 점수 하락", "④예산 증가"],
     "answer": 4},
    {"id": "A075", "num": 75, "type": "A",
     "question": "소셜 미디어 마케팅에서 '옴니채널(Omnichannel)' 전략의 특징은?",
     "options": ["①단일 채널에 집중한다", "②여러 채널을 통합하여 일관된 고객 경험을 제공한다", "③온라인 채널만 활용한다", "④각 채널을 독립적으로 운영한다"],
     "answer": 2},
    {"id": "A076", "num": 76, "type": "A",
     "question": "인스타그램 '가이드(Guides)' 기능의 주요 용도로 적절한 것은?",
     "options": ["①실시간 방송 진행", "②여러 게시물이나 제품을 큐레이션하여 제공", "③광고 집행", "④스토리 하이라이트 관리"],
     "answer": 2},
    {"id": "A077", "num": 77, "type": "A",
     "question": "소셜 미디어 광고에서 '게재 빈도 상한(Frequency Cap)'을 설정하는 이유는?",
     "options": ["①광고 노출을 극대화하기 위해", "②동일 사용자에게 과도한 광고 노출을 방지하기 위해", "③예산을 빠르게 소진하기 위해", "④새로운 타겟을 발굴하기 위해"],
     "answer": 2},
    {"id": "A078", "num": 78, "type": "A",
     "question": "소셜 미디어 마케팅에서 '퍼소나(Persona)' 개발의 목적은?",
     "options": ["①광고 예산 절감", "②타겟 고객을 구체적으로 이해하고 마케팅 전략 수립", "③경쟁사 분석", "④콘텐츠 자동화"],
     "answer": 2},
    {"id": "A079", "num": 79, "type": "A",
     "question": "유튜브 채널에서 '재생목록(Playlist)'을 활용하는 주요 이점이 아닌 것은?",
     "options": ["①시청 시간 증가", "②채널 구성 체계화", "③SEO 개선", "④구독자 자동 증가"],
     "answer": 4},
    {"id": "A080", "num": 80, "type": "A",
     "question": "소셜 미디어 마케팅에서 '게릴라 마케팅(Guerrilla Marketing)'의 특징으로 가장 적절한 것은?",
     "options": ["①대규모 예산이 필요하다", "②창의적인 방법으로 예상치 못한 장소에서 관심을 끈다", "③전통적인 광고 방식을 따른다", "④대형 브랜드만 활용할 수 있다"],
     "answer": 2},

    # === B형 (81-160) ===
    {"id": "B001", "num": 81, "type": "B",
     "question": "SNS 광고에서 '전환 캠페인' 목표 설정 시 가장 중요한 선행 조건은?",
     "options": ["①팔로워 수 확보", "②픽셀 또는 전환 API 설치 및 이벤트 설정", "③동영상 콘텐츠 준비", "④인플루언서 섭외"],
     "answer": 2},
    {"id": "B002", "num": 82, "type": "B",
     "question": "인스타그램 쇼핑 기능을 활성화하기 위한 필수 조건이 아닌 것은?",
     "options": ["①비즈니스 계정", "②페이스북 카탈로그 연동", "③최소 10,000 팔로워", "④판매 가능한 실물 제품"],
     "answer": 3},
    {"id": "B003", "num": 83, "type": "B",
     "question": "소셜 미디어 마케팅에서 '콘텐츠 믹스(Content Mix)' 전략으로 권장되는 비율 중 '80/20 법칙'이란?",
     "options": ["①80% 광고, 20% 정보", "②80% 가치 있는 콘텐츠, 20% 프로모션", "③80% 동영상, 20% 이미지", "④80% 유료, 20% 무료"],
     "answer": 2},
    {"id": "B004", "num": 84, "type": "B",
     "question": "카카오톡 채널 메시지 발송 시 주의사항으로 적절하지 않은 것은?",
     "options": ["①스팸성 메시지 발송 금지", "②개인정보 수집 동의 필요", "③수신 거부 옵션 제공", "④24시간 언제든지 대량 발송 가능"],
     "answer": 4},
    {"id": "B005", "num": 85, "type": "B",
     "question": "소셜 미디어 광고 소재 테스트 방법 중 '멀티변량 테스트(Multivariate Test)'의 특징은?",
     "options": ["①하나의 변수만 테스트한다", "②여러 변수의 조합을 동시에 테스트한다", "③두 개의 버전만 비교한다", "④수동으로 결과를 분석한다"],
     "answer": 2},
    {"id": "B006", "num": 86, "type": "B",
     "question": "유튜브 쇼츠(Shorts)의 최대 길이는?",
     "options": ["①30초", "②60초", "③90초", "④3분"],
     "answer": 3},
    {"id": "B007", "num": 87, "type": "B",
     "question": "페이스북 광고에서 '오프라인 전환(Offline Conversions)' 추적의 목적은?",
     "options": ["①온라인 광고 클릭 추적", "②광고 노출 후 오프라인 매장 구매 연결", "③웹사이트 트래픽 분석", "④앱 설치 추적"],
     "answer": 2},
    {"id": "B008", "num": 88, "type": "B",
     "question": "소셜 미디어에서 '알고리즘(Algorithm)'이 콘텐츠를 노출하는 방식을 이해하는 것이 중요한 이유는?",
     "options": ["①광고비를 절감하기 위해", "②콘텐츠가 더 많은 사람에게 도달하도록 최적화하기 위해", "③팔로워 수를 빠르게 늘리기 위해", "④경쟁사 콘텐츠를 분석하기 위해"],
     "answer": 2},
    {"id": "B009", "num": 89, "type": "B",
     "question": "인플루언서 마케팅에서 '가짜 팔로워(Fake Followers)'를 검증하는 방법으로 적절하지 않은 것은?",
     "options": ["①팔로워 대비 참여율 분석", "②팔로워 계정 활동성 검토", "③인플루언서 자체 신고", "④제3자 분석 툴 활용"],
     "answer": 3},
    {"id": "B010", "num": 90, "type": "B",
     "question": "소셜 미디어 광고의 '입찰 전략(Bid Strategy)' 중 '최저 비용(Lowest Cost)'의 특징은?",
     "options": ["①목표 CPA를 직접 설정한다", "②예산 내 최대한 많은 결과를 얻도록 자동 최적화한다", "③수동으로 입찰가를 설정한다", "④도달을 최우선으로 한다"],
     "answer": 2},
    {"id": "B011", "num": 91, "type": "B",
     "question": "네이버 검색광고에서 '품질지수(Quality Index)'에 영향을 미치는 요소가 아닌 것은?",
     "options": ["①광고 클릭률", "②랜딩 페이지 품질", "③광고주 예산 규모", "④키워드 관련성"],
     "answer": 3},
    {"id": "B012", "num": 92, "type": "B",
     "question": "소셜 미디어 마케팅에서 '감성 마케팅(Emotional Marketing)'의 목적으로 가장 적절한 것은?",
     "options": ["①가격 경쟁력 강조", "②소비자의 감정에 호소하여 브랜드 친밀감 형성", "③제품 기능 상세 설명", "④경쟁사 비교 분석"],
     "answer": 2},
    {"id": "B013", "num": 93, "type": "B",
     "question": "페이스북/인스타그램 광고에서 '자동 배치(Automatic Placement)'의 장점은?",
     "options": ["①특정 배치에만 집중할 수 있다", "②알고리즘이 최적의 배치를 자동 선택하여 성과 최적화", "③광고주가 모든 배치를 직접 제어한다", "④비용이 항상 낮아진다"],
     "answer": 2},
    {"id": "B014", "num": 94, "type": "B",
     "question": "소셜 미디어 마케팅에서 '아이겐(Earned Media)'에 해당하는 것은?",
     "options": ["①유료 광고", "②자사 SNS 채널", "③고객 리뷰 및 구전", "④스폰서 콘텐츠"],
     "answer": 3},
    {"id": "B015", "num": 95, "type": "B",
     "question": "틱톡 광고에서 '인피드 광고(In-Feed Ads)'가 노출되는 위치는?",
     "options": ["①앱 실행 시 전체 화면", "②사용자 피드 내 동영상 사이", "③검색 결과 상단", "④프로필 페이지"],
     "answer": 2},
    {"id": "B016", "num": 96, "type": "B",
     "question": "소셜 미디어 광고에서 '리드 광고(Lead Ads)'의 주요 특징은?",
     "options": ["①웹사이트로 이동하여 양식을 작성한다", "②소셜 미디어 내에서 바로 리드 정보를 수집한다", "③전화 연결로 리드를 수집한다", "④이메일로 리드 정보를 발송한다"],
     "answer": 2},
    {"id": "B017", "num": 97, "type": "B",
     "question": "소셜 미디어 마케팅에서 '콘텐츠 큐레이션(Content Curation)'의 의미는?",
     "options": ["①새로운 콘텐츠를 직접 제작하는 것", "②기존 콘텐츠를 선별하고 편집하여 공유하는 것", "③광고 콘텐츠를 구매하는 것", "④콘텐츠 삭제 및 관리"],
     "answer": 2},
    {"id": "B018", "num": 98, "type": "B",
     "question": "유튜브 광고에서 '건너뛸 수 있는 인스트림 광고'의 과금 기준으로 올바른 것은?",
     "options": ["①광고 노출 시", "②5초 시청 시", "③30초 이상 시청하거나 끝까지 시청했을 때", "④광고 클릭 시만"],
     "answer": 3},
    {"id": "B019", "num": 99, "type": "B",
     "question": "소셜 미디어 마케팅에서 '그로스 해킹(Growth Hacking)'의 핵심은?",
     "options": ["①대규모 광고 집행", "②데이터 기반 실험으로 빠른 성장 달성", "③전통적 마케팅 기법 활용", "④장기적 브랜드 구축"],
     "answer": 2},
    {"id": "B020", "num": 100, "type": "B",
     "question": "카카오 광고 플랫폼(카카오 모먼트)에서 '전환 목표' 캠페인 집행 시 필요한 것은?",
     "options": ["①카카오 픽셀 설치", "②카카오스토리 팔로워", "③카카오톡 채널 친구", "④카카오맵 등록"],
     "answer": 1},
    {"id": "B021", "num": 101, "type": "B",
     "question": "소셜 미디어 광고에서 '어드밴티지+(Advantage+)' 또는 '스마트 캠페인'의 특징은?",
     "options": ["①광고주가 모든 설정을 수동으로 제어한다", "②AI/머신러닝이 자동으로 광고 최적화를 진행한다", "③오직 이미지 광고만 지원한다", "④소규모 예산에는 사용할 수 없다"],
     "answer": 2},
    {"id": "B022", "num": 102, "type": "B",
     "question": "인스타그램에서 '클로즈 프렌즈(Close Friends)' 기능을 마케팅에 활용하는 방법으로 적절한 것은?",
     "options": ["①모든 팔로워에게 동일한 콘텐츠 발송", "②선별된 VIP 고객에게 독점 콘텐츠 제공", "③광고 집행 전용 기능으로 활용", "④경쟁사 계정 차단에 활용"],
     "answer": 2},
    {"id": "B023", "num": 103, "type": "B",
     "question": "소셜 미디어 마케팅 성과 보고서 작성 시 포함해야 할 핵심 지표가 아닌 것은?",
     "options": ["①도달수", "②참여율", "③경쟁사 직원 수", "④전환율"],
     "answer": 3},
    {"id": "B024", "num": 104, "type": "B",
     "question": "페이스북 광고에서 '예산 최적화 캠페인(CBO: Campaign Budget Optimization)'의 특징은?",
     "options": ["①각 광고 세트별로 예산을 수동 설정한다", "②캠페인 레벨 예산을 성과에 따라 자동 배분한다", "③광고 레벨에서 예산을 최적화한다", "④예산 변경이 불가능하다"],
     "answer": 2},
    {"id": "B025", "num": 105, "type": "B",
     "question": "소셜 미디어에서 '라이브 커머스(Live Commerce)'의 특징으로 적절하지 않은 것은?",
     "options": ["①실시간 소통이 가능하다", "②즉각적인 구매 유도가 가능하다", "③사전 녹화 영상만 사용한다", "④제품 시연이 가능하다"],
     "answer": 3},
    {"id": "B026", "num": 106, "type": "B",
     "question": "네이버 광고에서 '쇼핑 검색 광고'의 과금 방식은?",
     "options": ["①CPM", "②CPC", "③CPA", "④CPV"],
     "answer": 2},
    {"id": "B027", "num": 107, "type": "B",
     "question": "소셜 미디어 마케팅에서 '콘텐츠 리퍼포징(Content Repurposing)'이란?",
     "options": ["①콘텐츠를 삭제하고 재작성", "②기존 콘텐츠를 다른 형식으로 변환하여 재활용", "③광고 콘텐츠를 구매하여 사용", "④경쟁사 콘텐츠를 모방"],
     "answer": 2},
    {"id": "B028", "num": 108, "type": "B",
     "question": "인스타그램 광고에서 '컬렉션 광고(Collection Ad)'의 특징은?",
     "options": ["①단일 이미지만 표시된다", "②커버 이미지/동영상과 여러 제품을 함께 표시한다", "③텍스트만 포함된다", "④스토리에만 게재된다"],
     "answer": 2},
    {"id": "B029", "num": 109, "type": "B",
     "question": "소셜 미디어 마케팅에서 '바이럴 마케팅(Viral Marketing)'의 성공 요소가 아닌 것은?",
     "options": ["①공유하고 싶은 감정 유발", "②높은 광고 예산", "②쉬운 공유 메커니즘", "④타이밍"],
     "answer": 2},
    {"id": "B030", "num": 110, "type": "B",
     "question": "유튜브 '채널 멤버십(Channel Membership)' 기능의 특징으로 적절하지 않은 것은?",
     "options": ["①월정액 구독 형태", "②멤버 전용 콘텐츠 제공", "③자동 광고 수익 분배", "④배지 및 이모지 제공"],
     "answer": 3},
    {"id": "B031", "num": 111, "type": "B",
     "question": "소셜 미디어 광고에서 '픽셀 이벤트(Pixel Event)' 중 '구매(Purchase)' 이벤트를 추적하는 목적은?",
     "options": ["①웹사이트 방문자 추적", "②실제 매출과 광고 성과 연결", "③앱 설치 추적", "④이메일 수집"],
     "answer": 2},
    {"id": "B032", "num": 112, "type": "B",
     "question": "소셜 미디어 마케팅에서 '브랜드 일관성(Brand Consistency)'을 위해 관리해야 할 요소가 아닌 것은?",
     "options": ["①로고와 색상", "②어조와 목소리", "③경쟁사 마케팅 예산", "④메시지 방향성"],
     "answer": 3},
    {"id": "B033", "num": 113, "type": "B",
     "question": "카카오 광고에서 '카카오 친구톡'의 발송 대상은?",
     "options": ["①모든 카카오톡 사용자", "②카카오톡 채널 친구 추가 사용자", "③카카오스토리 팔로워", "④카카오맵 사용자"],
     "answer": 2},
    {"id": "B034", "num": 114, "type": "B",
     "question": "소셜 미디어 마케팅에서 '소셜 커머스(Social Commerce)'의 특징으로 적절하지 않은 것은?",
     "options": ["①SNS 플랫폼 내 구매 완결", "②소셜 데이터 기반 상품 추천", "③오직 텍스트 기반 거래", "④공유와 구매의 결합"],
     "answer": 3},
    {"id": "B035", "num": 115, "type": "B",
     "question": "인스타그램 '브랜디드 콘텐츠 광고(Branded Content Ads)'에서 광고주가 할 수 있는 것은?",
     "options": ["①인플루언서의 유기적 게시물을 광고로 촉진", "②인플루언서 계정 직접 운영", "③인플루언서 팔로워 데이터 열람", "④인플루언서 콘텐츠 무단 수정"],
     "answer": 1},
    {"id": "B036", "num": 116, "type": "B",
     "question": "소셜 미디어 광고에서 '스플릿 테스트(Split Test)'를 진행할 때 테스트 변수로 활용하기 어려운 것은?",
     "options": ["①광고 소재", "②타겟 고객", "③경쟁사 광고 내용", "④광고 배치"],
     "answer": 3},
    {"id": "B037", "num": 117, "type": "B",
     "question": "유튜브 광고에서 '비디오 액션 캠페인(Video Action Campaign)'의 주요 특징은?",
     "options": ["①브랜드 인지도만을 목표로 한다", "②전환 유도를 위한 CTA가 포함된 광고", "③오직 범퍼 광고 형식만 사용한다", "④유튜브 외 구글 네트워크에서는 노출되지 않는다"],
     "answer": 2},
    {"id": "B038", "num": 118, "type": "B",
     "question": "소셜 미디어 마케팅에서 '세그멘테이션(Segmentation)'의 기준이 아닌 것은?",
     "options": ["①인구통계적 기준", "②지리적 기준", "③경쟁사 브랜드명", "④심리적 기준"],
     "answer": 3},
    {"id": "B039", "num": 119, "type": "B",
     "question": "소셜 미디어 광고에서 '전환 API(Conversions API)'의 주요 장점은?",
     "options": ["①광고 소재 자동 생성", "②브라우저 쿠키 제한을 우회하여 더 정확한 전환 추적", "③타겟 자동 확장", "④예산 자동 최적화"],
     "answer": 2},
    {"id": "B040", "num": 120, "type": "B",
     "question": "소셜 미디어 마케팅에서 '포지셔닝(Positioning)'의 핵심은?",
     "options": ["①가격 경쟁에서 우위를 점하는 것", "②경쟁사와 차별화된 브랜드 인식을 만드는 것", "③가장 많은 팔로워를 확보하는 것", "④모든 고객층을 대상으로 하는 것"],
     "answer": 2},
    {"id": "B041", "num": 121, "type": "B",
     "question": "인스타그램 '릴스 광고(Reels Ads)'의 형식으로 올바른 것은?",
     "options": ["①가로형 동영상", "②정사각형 이미지", "③세로형 전체 화면 동영상", "④텍스트 전용"],
     "answer": 3},
    {"id": "B042", "num": 122, "type": "B",
     "question": "소셜 미디어 마케팅에서 '게이미피케이션(Gamification)'을 활용한 마케팅의 예가 아닌 것은?",
     "options": ["①포인트 적립 시스템", "②배지 획득 이벤트", "③가격 인하 프로모션", "④리더보드 경쟁"],
     "answer": 3},
    {"id": "B043", "num": 123, "type": "B",
     "question": "유튜브 '슈퍼챗(Super Chat)' 기능의 특징으로 옳은 것은?",
     "options": ["①광고 수익의 일부를 크리에이터에게 지급", "②시청자가 라이브 채팅에서 유료로 메시지를 강조 표시", "③구독자 전용 콘텐츠 제공", "④채널 멤버십 자동 가입"],
     "answer": 2},
    {"id": "B044", "num": 124, "type": "B",
     "question": "소셜 미디어 광고에서 '어드밴티지 타겟팅(Advantage Targeting)'의 특징은?",
     "options": ["①광고주가 수동으로 모든 타겟을 설정한다", "②AI가 설정된 타겟 외 더 좋은 성과의 타겟을 자동 발굴", "③오직 맞춤 타겟만 사용한다", "④타겟 변경이 불가능하다"],
     "answer": 2},
    {"id": "B045", "num": 125, "type": "B",
     "question": "소셜 미디어 마케팅에서 '참여형 콘텐츠(Interactive Content)'의 예가 아닌 것은?",
     "options": ["①투표/설문", "②퀴즈", "③제품 카탈로그 PDF", "④Q&A 세션"],
     "answer": 3},
    {"id": "B046", "num": 126, "type": "B",
     "question": "페이스북 광고에서 '관련성 점수(Relevance Score, 현 품질 순위)'가 높을 때의 효과는?",
     "options": ["①광고 비용이 증가한다", "②광고 배포 효율이 높아지고 비용이 낮아질 수 있다", "③광고 노출이 감소한다", "④타겟 범위가 좁아진다"],
     "answer": 2},
    {"id": "B047", "num": 127, "type": "B",
     "question": "소셜 미디어 광고에서 '랜딩 페이지(Landing Page)' 최적화의 핵심 요소가 아닌 것은?",
     "options": ["①명확한 CTA", "②빠른 로딩 속도", "②모바일 최적화", "④경쟁사 비교 링크 삽입"],
     "answer": 4},
    {"id": "B048", "num": 128, "type": "B",
     "question": "틱톡 '브랜드 해시태그 챌린지(Branded Hashtag Challenge)'의 주요 목적은?",
     "options": ["①직접적인 제품 판매", "②사용자 참여 유도 및 바이럴 확산", "③경쟁사 분석", "④고객 서비스 개선"],
     "answer": 2},
    {"id": "B049", "num": 129, "type": "B",
     "question": "소셜 미디어 마케팅에서 '콘텐츠 배포 전략' 중 '채널 적합성'을 고려할 때 링크드인(LinkedIn)에 가장 적합한 콘텐츠는?",
     "options": ["①15초 댄스 챌린지", "②B2B 산업 인사이트 및 전문 지식", "③제품 언박싱 동영상", "④음식 레시피"],
     "answer": 2},
    {"id": "B050", "num": 130, "type": "B",
     "question": "소셜 미디어 광고에서 '노출 공유(Impression Share)'가 낮을 때의 원인이 아닌 것은?",
     "options": ["①예산 부족", "②입찰가 부족", "③광고 품질 낮음", "④팔로워 수 증가"],
     "answer": 4},
    {"id": "B051", "num": 131, "type": "B",
     "question": "소셜 미디어 마케팅에서 '다크 포스트(Dark Post)'의 특징은?",
     "options": ["①모든 팔로워에게 공개된다", "②광고 계정을 통해 집행되며 페이지 피드에 나타나지 않는다", "③오직 동영상 형식으로만 존재한다", "④특정 국가에서만 사용 가능하다"],
     "answer": 2},
    {"id": "B052", "num": 132, "type": "B",
     "question": "네이버 검색광고 '파워컨텐츠' 광고의 특징으로 올바른 것은?",
     "options": ["①배너 형태로 노출된다", "②블로그, 카페 등 콘텐츠가 검색 결과에 광고로 노출된다", "③동영상 전용 광고이다", "④유튜브에서도 노출된다"],
     "answer": 2},
    {"id": "B053", "num": 133, "type": "B",
     "question": "소셜 미디어 광고에서 '광고 경매(Ad Auction)'에서 낙찰되는 기준으로 옳은 것은?",
     "options": ["①가장 높은 입찰가", "②입찰가 + 예상 행동률 + 광고 품질의 총 가치", "③광고주의 계정 규모", "④가장 긴 광고 집행 기간"],
     "answer": 2},
    {"id": "B054", "num": 134, "type": "B",
     "question": "소셜 미디어 마케팅에서 '앰버서더 프로그램(Ambassador Program)'의 특징으로 적절하지 않은 것은?",
     "options": ["①장기적 브랜드 대표자 육성", "②진정성 있는 브랜드 홍보", "③단기 일회성 협업", "④커뮤니티 리더십 활용"],
     "answer": 3},
    {"id": "B055", "num": 135, "type": "B",
     "question": "유튜브 광고에서 'CPV(Cost Per View)'의 조회 기준으로 올바른 것은?",
     "options": ["①1초 이상 시청", "②5초 이상 시청하거나 광고 클릭", "③30초 이상 시청", "④영상 끝까지 시청"],
     "answer": 2},
    {"id": "B056", "num": 136, "type": "B",
     "question": "소셜 미디어 광고에서 '잠재고객 세분화(Audience Segmentation)'의 목적으로 가장 적절한 것은?",
     "options": ["①광고 예산 증가", "②각 세그먼트에 맞는 맞춤형 메시지 전달", "③팔로워 일괄 관리", "④동일한 광고를 모든 사람에게 노출"],
     "answer": 2},
    {"id": "B057", "num": 137, "type": "B",
     "question": "소셜 미디어 마케팅에서 '공동 마케팅(Co-marketing)'의 특징으로 적절하지 않은 것은?",
     "options": ["①두 브랜드가 함께 마케팅 진행", "②비용 및 자원 공유", "③경쟁 관계에 있는 브랜드와만 진행", "④새로운 고객층 접근 가능"],
     "answer": 3},
    {"id": "B058", "num": 138, "type": "B",
     "question": "페이스북/인스타그램 광고에서 '카탈로그(Catalog)'를 활용하는 광고 형식은?",
     "options": ["①리드 광고", "②다이나믹 광고", "③전화 유도 광고", "④설문 광고"],
     "answer": 2},
    {"id": "B059", "num": 139, "type": "B",
     "question": "소셜 미디어에서 '알고리즘 업데이트'에 적응하는 전략으로 적절하지 않은 것은?",
     "options": ["①콘텐츠 품질 향상", "②참여 유도 강화", "③팔로워 구매", "④다양한 콘텐츠 형식 실험"],
     "answer": 3},
    {"id": "B060", "num": 140, "type": "B",
     "question": "소셜 미디어 마케팅에서 '인플루언서 마케팅 플랫폼'의 주요 기능이 아닌 것은?",
     "options": ["①인플루언서 검색 및 발굴", "②캠페인 관리", "③성과 분석", "④광고 소재 자동 제작"],
     "answer": 4},
    {"id": "B061", "num": 141, "type": "B",
     "question": "소셜 미디어 광고에서 '멀티채널 캠페인(Multi-channel Campaign)'의 장점으로 적절하지 않은 것은?",
     "options": ["①더 넓은 도달 범위", "②일관된 브랜드 메시지", "③관리 복잡성 감소", "④채널별 최적화 가능"],
     "answer": 3},
    {"id": "B062", "num": 142, "type": "B",
     "question": "인스타그램에서 '스폰서드(Sponsored)' 표시 의미는?",
     "options": ["①인기 게시물", "②팔로우하는 계정의 게시물", "③광고로 게재된 콘텐츠", "④인증된 계정의 게시물"],
     "answer": 3},
    {"id": "B063", "num": 143, "type": "B",
     "question": "소셜 미디어 마케팅에서 '아젠다 세팅(Agenda Setting)' 이론을 적용한 전략은?",
     "options": ["①무작위 콘텐츠 발행", "②특정 주제에 대한 인식을 형성하도록 콘텐츠 기획", "③경쟁사 비난 콘텐츠 제작", "④광고 예산 최대화"],
     "answer": 2},
    {"id": "B064", "num": 144, "type": "B",
     "question": "소셜 미디어 광고에서 '계절성(Seasonality)'을 고려한 마케팅 전략으로 적절하지 않은 것은?",
     "options": ["①성수기 전 예산 증가", "②시즌별 맞춤 크리에이티브 제작", "③비수기 완전 광고 중단", "④연간 마케팅 캘린더 수립"],
     "answer": 3},
    {"id": "B065", "num": 145, "type": "B",
     "question": "유튜브에서 '커뮤니티 가이드라인 경고(Community Guidelines Strike)'의 결과가 아닌 것은?",
     "options": ["①채널 기능 일부 제한", "②수익 창출 중단", "③경고 누적 시 채널 삭제", "④경쟁사 채널 자동 추천"],
     "answer": 4},
    {"id": "B066", "num": 146, "type": "B",
     "question": "소셜 미디어 광고에서 '광고 심사(Ad Review)' 기준을 위반하는 콘텐츠가 아닌 것은?",
     "options": ["①허위 또는 과장된 주장", "②차별적 표현", "③실제 제품 이미지 사용", "④저작권 침해 콘텐츠"],
     "answer": 3},
    {"id": "B067", "num": 147, "type": "B",
     "question": "소셜 미디어 마케팅에서 '퍼블리셔(Publisher) 전략'이란?",
     "options": ["①광고만 집행하는 전략", "②자사 미디어를 구축하여 지속적으로 콘텐츠를 발행하는 전략", "③인플루언서에게 콘텐츠 제작을 전적으로 맡기는 전략", "④유료 광고에만 의존하는 전략"],
     "answer": 2},
    {"id": "B068", "num": 148, "type": "B",
     "question": "카카오 광고에서 '디스플레이 광고'가 노출되는 매체가 아닌 것은?",
     "options": ["①카카오톡", "②카카오스토리", "③다음(Daum)", "④네이버 블로그"],
     "answer": 4},
    {"id": "B069", "num": 149, "type": "B",
     "question": "소셜 미디어 마케팅에서 '제품 리뷰(Product Review)' 마케팅의 장점으로 적절하지 않은 것은?",
     "options": ["①신뢰도 향상", "②구매 결정 지원", "③완벽한 통제 가능", "④SEO 효과"],
     "answer": 3},
    {"id": "B070", "num": 150, "type": "B",
     "question": "소셜 미디어 광고에서 '광고 예산 최적화(Budget Optimization)'를 위한 전략으로 적절하지 않은 것은?",
     "options": ["①성과 낮은 광고 세트 예산 조정", "②A/B 테스트를 통한 최적 소재 선별", "③모든 예산을 단일 채널에 집중", "④성수기와 비수기 예산 차등 적용"],
     "answer": 3},
    {"id": "B071", "num": 151, "type": "B",
     "question": "인스타그램 광고에서 '슬라이드(Carousel) 광고'의 특징으로 적절하지 않은 것은?",
     "options": ["①여러 이미지/동영상을 슬라이드로 표시", "②각 슬라이드에 다른 링크 설정 가능", "③단일 랜딩 페이지만 연결 가능", "④스토리텔링에 적합"],
     "answer": 3},
    {"id": "B072", "num": 152, "type": "B",
     "question": "소셜 미디어 마케팅에서 '아이콘텐츠(Iconic Content)'를 만드는 전략으로 적절하지 않은 것은?",
     "options": ["①독특한 브랜드 개성 반영", "②일관된 시각적 아이덴티티", "③경쟁사 콘텐츠 복사", "④강렬한 감정적 연결"],
     "answer": 3},
    {"id": "B073", "num": 153, "type": "B",
     "question": "소셜 미디어 광고에서 '지오타겟팅(Geo-targeting)'의 활용 예로 가장 적합한 것은?",
     "options": ["①전국 브랜드 인지도 캠페인", "②특정 지역 매장 방문 유도 캠페인", "③글로벌 앱 다운로드 캠페인", "④전 연령대 대상 캠페인"],
     "answer": 2},
    {"id": "B074", "num": 154, "type": "B",
     "question": "유튜브 '파트너 프로그램(YPP)' 가입 조건 중 구독자 수 요건은?",
     "options": ["①100명", "②500명", "③1,000명", "④10,000명"],
     "answer": 3},
    {"id": "B075", "num": 155, "type": "B",
     "question": "소셜 미디어 마케팅에서 '사회적 책임(CSR: Corporate Social Responsibility)' 마케팅이 소비자에게 미치는 주요 영향은?",
     "options": ["①가격 인하 기대", "②브랜드 신뢰도 및 호감도 향상", "③제품 성능에 대한 기대 증가", "④경쟁사 제품 불신"],
     "answer": 2},
    {"id": "B076", "num": 156, "type": "B",
     "question": "소셜 미디어 광고에서 '플리킹(Phishing)' 방지를 위해 광고주가 해야 할 것은?",
     "options": ["①광고에 실제 브랜드 URL 명시", "②더 많은 광고 집행", "③팔로워 수 증가", "④동영상 광고로 전환"],
     "answer": 1},
    {"id": "B077", "num": 157, "type": "B",
     "question": "소셜 미디어 마케팅에서 '고객 생애 가치(CLV: Customer Lifetime Value)'를 높이는 전략으로 적절하지 않은 것은?",
     "options": ["①로열티 프로그램 운영", "②재구매 유도 캠페인", "③신규 고객 확보에만 집중", "④개인화된 서비스 제공"],
     "answer": 3},
    {"id": "B078", "num": 158, "type": "B",
     "question": "소셜 미디어 광고에서 '시퀀셜 광고(Sequential Advertising)'의 목적은?",
     "options": ["①동일한 광고를 반복 노출", "②단계별로 다른 메시지를 순서대로 전달하여 스토리텔링", "③무작위로 다양한 광고를 노출", "④단일 노출로 전환 유도"],
     "answer": 2},
    {"id": "B079", "num": 159, "type": "B",
     "question": "유튜브 '콘텐츠 ID(Content ID)' 시스템의 주요 기능은?",
     "options": ["①채널 구독자 관리", "②저작권 보호 및 수익화 관리", "③광고 집행 자동화", "④댓글 필터링"],
     "answer": 2},
    {"id": "B080", "num": 160, "type": "B",
     "question": "소셜 미디어 마케팅 전략 수립 시 'SMART 목표' 설정에서 'M(Measurable)'의 의미는?",
     "options": ["①달성 가능한", "②측정 가능한", "③구체적인", "④관련성 있는"],
     "answer": 2},
]

SYSTEM_PROMPT = """당신은 SNS광고마케터 1급 시험 전문 강사입니다.
각 문제에 대해 다음 형식으로 정확하고 간결한 분석을 제공하세요:

【핵심】한 줄로 이 문제의 핵심 개념 설명
【키워드】이 문제와 관련된 핵심 키워드 2-3개
【선택지 분석】
① 선택지1 - 맞음/틀림 여부와 이유 (한 줄)
② 선택지2 - 맞음/틀림 여부와 이유 (한 줄)
③ 선택지3 - 맞음/틀림 여부와 이유 (한 줄)
④ 선택지4 - 맞음/틀림 여부와 이유 (한 줄)
【풀이 가이드】정답인 이유와 시험 출제 포인트 (2-3줄)"""

def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}

def save_progress(results):
    with open(PROGRESS_FILE, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

def generate_analysis(client, question):
    q_text = question['question']
    options = '\n'.join(question['options'])
    answer_num = question['answer']
    answer_text = question['options'][answer_num - 1]

    prompt = f"""문제: {q_text}

선택지:
{options}

정답: {answer_num}번 - {answer_text}

위 문제에 대한 분석을 제공해주세요."""

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=800,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.content[0].text

def parse_analysis(text):
    result = {"핵심": "", "키워드": "", "선택지분석": "", "풀이가이드": ""}

    import re
    patterns = {
        "핵심": r'【핵심】(.+?)(?=【|$)',
        "키워드": r'【키워드】(.+?)(?=【|$)',
        "선택지분석": r'【선택지 분석】(.+?)(?=【|$)',
        "풀이가이드": r'【풀이 가이드】(.+?)(?=【|$)',
    }

    for key, pattern in patterns.items():
        m = re.search(pattern, text, re.DOTALL)
        if m:
            result[key] = m.group(1).strip()

    if not result["핵심"]:
        result["핵심"] = text[:100] if len(text) > 100 else text

    return result

def main():
    api_key = os.environ.get('ANTHROPIC_API_KEY')
    if not api_key:
        print("Error: ANTHROPIC_API_KEY not set")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)
    results = load_progress()

    total = len(QUESTIONS)
    completed = len(results)
    print(f"Starting: {completed}/{total} questions already completed")

    for i, q in enumerate(QUESTIONS):
        qid = q['id']
        if qid in results:
            continue

        print(f"[{i+1}/{total}] Processing {qid}: {q['question'][:40]}...")

        max_retries = 3
        for attempt in range(max_retries):
            try:
                analysis_text = generate_analysis(client, q)
                parsed = parse_analysis(analysis_text)

                results[qid] = {
                    "id": qid,
                    "num": q['num'],
                    "type": q['type'],
                    "question": q['question'],
                    "options": q['options'],
                    "answer": q['answer'],
                    "analysis": parsed,
                    "analysis_raw": analysis_text
                }

                save_progress(results)
                completed += 1
                print(f"  Done ({completed}/{total})")

                # Rate limiting: 0.5s between calls
                time.sleep(0.5)
                break

            except anthropic.RateLimitError:
                wait = 30 * (attempt + 1)
                print(f"  Rate limit hit, waiting {wait}s...")
                time.sleep(wait)
            except anthropic.APIError as e:
                print(f"  API error (attempt {attempt+1}): {e}")
                if attempt < max_retries - 1:
                    time.sleep(5)
                else:
                    print(f"  Failed after {max_retries} attempts, skipping")
            except Exception as e:
                print(f"  Unexpected error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(5)
                else:
                    print(f"  Skipping {qid}")

    # Build final output
    final_output = []
    for q in QUESTIONS:
        qid = q['id']
        if qid in results:
            final_output.append(results[qid])
        else:
            final_output.append({
                "id": qid,
                "num": q['num'],
                "type": q['type'],
                "question": q['question'],
                "options": q['options'],
                "answer": q['answer'],
                "analysis": None
            })

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(final_output, f, ensure_ascii=False, indent=2)

    succeeded = sum(1 for item in final_output if item.get('analysis'))
    print(f"\nComplete! {succeeded}/{total} questions have analysis.")
    print(f"Output saved to: {OUTPUT_FILE}")

if __name__ == '__main__':
    main()
